### ISSUE TITLE
Review 1: Back to menu fitur

### ISSUE THREAD

**Issue by priyandari** [rezawn/MultiCalculator#1]
Setelah mengerjakan sebuah proses kalkulator, misal konversi panjang.. tidak ada fitur untuk kembali ke menu awal memilih berbagai jenis fitur yang bisa dilakukan oleh kalkulator

**Comment by rezawn** [comment]
Algoritma program yang berkaitan dengan issue ini telah kami perbaiki pak. Terdapat penggabungan algoritma setiap fitur dan didalam setiap fitur program telah kami tambahkan menu untuk kembali ke menu awal program
