### ISSUE TITLE
Review 1: Berat badan ideal

### ISSUE THREAD

**Issue by priyandari** [rezawn/MultiCalculator#2]
MENGHITUNG BERAT BADAN IDEAL
Tinggi Badan dalam Satuan Cm : 167
Berat Badan Ideal (kg) :  60.3

Apakah berat ideal itu nilai fixed atau misal.. kalau dalam rentang 60 s.d. 62 masih dalam kategori ideal untuk seseorang dengan tinggi 167 ?

**Comment by AcintyaUdanArum** [comment]
Maaf pak sebelumnya, dalam program ini, kami menggunakan perhitungan BBI dengan metode Broca dimana untuk rentang berat badan hanya terdapat dalam perhitungan berat badan pria dan wanita saja sedangkan untuk bayi, anak, dan wanita hamil merupakan nilai fix, apabila ingin mengetahui rentang berat badannya harus menggunakan rumus IMT dimana Indikator gemuk tidak nya seseorang dilihat dari rentang nilai indeks massa tubuh bukan berat badan aslinya, untuk perhitungan pria dan wanita sekarang sudah kami perbaiki🙏
