### ISSUE TITLE
Review 1: Algoritma dimana ?

### ISSUE THREAD

**Issue by priyandari** [rezawn/MultiCalculator#3]
Ini juga menjadi kebingungan pengguna:

Fitur 4 : Penggunaan modul requests, list, percabangan, dan perulangan

Diberikan pilihan offline atau online atau keluar

Pilih offline

Pengguna diminta menginputkan jenis mata uang pertama

Pengguna diminta menginputkan jenis mata uang kedua

Pengguna diminta menginputkan nilai tukar mata uang pertama dalam mata uang kedua

Diberikan pilihan konversi dari mata uang pertama atau kedua

Konversi dari mata uang pertama

Pengguna diminta menginputkan jumlah uang dalam mata uang pertama

Diberikan output jumlah uang dalam mata uang kedua

Diberikan pilihan untuk menggunakan kembali fitur, ya atau tidak

Jika ya maka pengguna diminta menginputkan jumlah uang kembali

Jika tidak maka Selesai

Konversi dari mata uang kedua

Pengguna diminta menginputkan jumlah uang dalam mata uang kedua

Diberikan output jumlah uang dalam mata uang pertama

Diberikan pilihan untuk menggunakan kembali fitur, ya atau tidak

Jika ya maka pengguna diminta menginputkan jumlah uang kembali

Jika tidak maka Selesai

**Comment by rezawn** [comment]
Algoritma program yang berkaitan dengan issue ini telah kami perbaiki pak. Kalimat-kalimat pertanyan untuk memperoleh data dari pengguna telah kami perbaiki dan juga ada sedikit perubahan pada alur algoritmanya sehingga program akan lebih mudah dipahami oleh pengguna
